// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gorilla/mux"
	"github.com/lordvidex/wordle-wf/internal/words"
)

// Injectors from wire.go:

func RegisterWordsHandler(parentRouter *mux.Router) *words.Handler {
	repository := words.NewRepository()
	service := words.NewService(repository)
	handler := words.RegisterHandler(parentRouter, service)
	return handler
}
