DROP TABLE IF EXISTS game_player_word CASCADE;
DROP TABLE IF EXISTS game_player CASCADE;
DROP TABLE IF EXISTS wordlewf_user CASCADE;
DROP TABLE IF EXISTS game_settings CASCADE;
DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS word CASCADE;
