DROP TABLE IF EXISTS game_session_guess CASCADE;
DROP TABLE IF EXISTS game_session CASCADE;
DROP TABLE IF EXISTS game_player CASCADE;
DROP TABLE IF EXISTS game_settings CASCADE;
DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS word CASCADE;
DROP DATABASE IF EXISTS wordle_wf;
